# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xdg-user-dirs
Summary:    Handles user special directories
Version:    0.14
Release:    1
Group:      User Interface/Desktops
License:    GPLv2
URL:        http://www.freedesktop.org/wiki/Software/xdg-user-dirs
Source0:    http://user-dirs.freedesktop.org/releases/%{name}-%{version}.tar.gz
Source100:  xdg-user-dirs.yaml
Patch0:     use-fuzzy.patch
Patch1:     meego-use-fuzzy-translations.patch
BuildRequires:  gettext


%description
Contains xdg-user-dirs-update that updates folders in a users
homedirectory based on the defaults configured by the administrator.


%package lang
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
%description lang
Development files for %{name}



%prep
%setup -q -n %{name}-%{version}

# use-fuzzy.patch
%patch0 -p1
# meego-use-fuzzy-translations.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post
%find_lang %name






%files -f %name.lang
%defattr(-,root,root,-)
# >> files
%doc NEWS AUTHORS README ChangeLog COPYING
%{_bindir}/*
%config(noreplace) %{_sysconfdir}/xdg/user-dirs.conf
%config(noreplace) %{_sysconfdir}/xdg/user-dirs.defaults
# << files

%files lang
%defattr(-,root,root,-)
# >> files lang
# << files lang


